volumes:
  redis_data:

services:
  backend:
    restart: always
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
    ports:
      - "${APP_PORT:-8000}:8000"
    command: |
        bash -c "
        gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60 --reload"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      
    environment:
      - PYTHONUNBUFFERED=0
      - APP_ENV=${APP_ENV}
      - OLLAMA_HOST=${OLLAMA_HOST}
    volumes:
      - ./backend/src:/code/src
      - ./backend/tests:/code/tests
      - ./backend/alembic.ini:/code/alembic.ini
      - ./backend/logconfig.yml:/code/logconfig.yml
  redis:
    image: redis:7-alpine
    container_name: physical-ai-redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
